version: '3.8'

services:
  web:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always  
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - static:/backend/static
      - media:/backend/media 
    expose:
      - 8000
    # env_file:
    #   - ./backend/.env
    depends_on:
      - db
      

  db:
    container_name: db
    restart: always
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "vrachat_prod"
      POSTGRES_USER: "vrachat"
      POSTGRES_PASSWORD: "vrachat"
    ports:
      - 5432:5432

  frontend:
    container_name: frontend
    build: frontend
    expose:
      - 8001
    environment:
      CI: false

  # redis:
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - /path/to/local/d–∞ta:/root/redis
  #     - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
  #   environment:
  #     - REDIS_PORT=6379
  #     - REDIS_DATABASES=16    

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    volumes:
      - static:/backend/static
      - media:/backend/media
    ports:
      - 80:80
    depends_on:
      - web

  # bot:
  #   container_name: bot
  #   build: ./bot
  #   restart: always
  #   env_file:
  #     - ./bot/.env
  #   command:  python runbot.py
  #   depends_on:
  #     - db

    


volumes:
  postgres_data:
  static:
  media: