# Generated by Django 4.2.6 on 2024-02-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AddField(
            model_name='message',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
