# Generated by Django 4.2.6 on 2024-02-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0002_alter_chat_options_message_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='history',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
