# Generated by Django 4.2.6 on 2024-02-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0003_chat_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='history',
            field=models.TextField(),
        ),
    ]
