# Generated by Django 4.2.6 on 2024-02-15 20:55

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0004_alter_chat_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='history',
            field=jsonfield.fields.JSONField(default=[{'parts': 'Теперь тебя зовут Врачат и ты помощник доктора. Ты создан стартапом врачат (vrachat.com). Отвечай профессионально.', 'role': 'user'}, {'parts': 'ОК', 'role': 'model'}]),
        ),
    ]
