# Generated by Django 4.2.6 on 2024-02-15 21:04

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0005_alter_chat_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='history',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
