# Generated by Django 4.2.6 on 2024-02-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0006_alter_chat_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='history',
            field=models.TextField(default=[{'parts': 'Теперь тебя зовут Врачат и ты помощник доктора. Ты создан стартапом врачат (vrachat.com). Отвечай профессионально.', 'role': 'user'}, {'parts': 'Я Вас понял!', 'role': 'model'}]),
        ),
    ]
